#!/bin/bash

# Misc. functions used by birb and birb packages
#
# If you want to source birb packages, you might need
# to source this file first to avoid errors related to
# missing functions
#
# This file also helps to off-load some of the stuff from
# the main birb script to another file to not have one huge
# file containing everything

# Logging functions
println()
{
	case $1 in
		ERROR) echo -e "\e[31mERROR: $2\e[0m" ;;
		WARNING) echo -e "\e[35mWARNING: $2\e[0m" ;;
		*) echo -e "\e[32m=> \e[0m$@" ;;
	esac
}


# Version parsing helper functions

# Transform a version string X.X.X to X.X taking out the patch number
# Args: [version]
short_version()
{
	echo $1 | awk -F'.' '{print $1 "." $2}'
}

# Transform a version string X.X.X to X leaving only the major version
# This will also convert version X.X to X
# Args: [version]
major_version()
{
	echo $1 | cut -d'.' -f1
}
