name: Linting checks

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main", "dev" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: cppcheck shellcheck
        version: 1.0
    - name: ShellCheck
      run: make check_sh
    - name: CppCheck
      run: make check_cpp
